# Generated by Django 5.2 on 2025-07-22 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(default='')),
                ('value', models.IntegerField(default=1)),
                ('cost_quantity', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='LandUnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('production', models.JSONField(default=dict)),
                ('harvest', models.IntegerField(default=1)),
                ('base_population_capacity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MercenaryUnitSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('gold_cost_recruitment_modifier', models.DecimalField(decimal_places=3, default=1.0, max_digits=5)),
                ('food_cost_upkeep', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='MilitaryUnitSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('gold_cost_upkeep', models.IntegerField(default=1, help_text='Base gold cost for upkeep per unit of this size category per year.')),
                ('food_cost_upkeep', models.IntegerField(default=1, help_text='Base food cost for upkeep per unit of this size category per year.')),
            ],
        ),
        migrations.CreateModel(
            name='PopulationRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Realm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ruler', models.CharField(max_length=100)),
                ('treasury', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('year', models.IntegerField(default=1)),
                ('loyalty_population', models.IntegerField(default=0)),
                ('loyalty_military', models.IntegerField(default=0)),
                ('loyalty_mercenaries', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RealmScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(default='')),
                ('pop_unit_size', models.IntegerField(default=1)),
                ('land_unit_size', models.IntegerField(default=1)),
                ('gold_unit_value', models.IntegerField(default=1)),
                ('military_unit_size', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('gold_cost_display', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(help_text='Order for sorting seasons (e.g., 1 for Spring).', unique=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StrongholdType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('duration_seasons', models.PositiveIntegerField(default=1, help_text='Number of seasons (turns) it takes to build.')),
                ('population_cost', models.PositiveIntegerField(default=1, help_text='Population units required for construction.')),
                ('resource_costs', models.JSONField(default=dict, help_text="JSON dictionary of resource costs, e.g., {'Wood': 50, 'Stone': 20}")),
                ('gold_cost', models.PositiveIntegerField(default=0, help_text='Gold cost for construction.')),
                ('population_capacity_bonus', models.IntegerField(default=0, help_text='Bonus to population capacity.')),
            ],
        ),
        migrations.CreateModel(
            name='LandUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('upgrades', models.JSONField(default=list)),
                ('mineral_type', models.CharField(blank=True, max_length=50, null=True)),
                ('has_roads', models.BooleanField(default=False)),
                ('has_mine', models.BooleanField(default=False)),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realms.landunittype')),
            ],
        ),
        migrations.CreateModel(
            name='PopulationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pop_units', to='realms.landunit')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realms.populationrace')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='population_units', to='realms.realm')),
            ],
        ),
        migrations.AddField(
            model_name='landunit',
            name='assigned_population',
            field=models.ManyToManyField(blank=True, related_name='located_in_land_units', to='realms.populationunit'),
        ),
        migrations.CreateModel(
            name='OngoingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=100)),
                ('start_season', models.CharField(max_length=10)),
                ('start_year', models.IntegerField()),
                ('duration', models.IntegerField(default=1)),
                ('completed', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, null=True)),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realms.realm')),
            ],
        ),
        migrations.AddField(
            model_name='landunit',
            name='realm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_units', to='realms.realm'),
        ),
        migrations.CreateModel(
            name='RealmGoodsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('goods_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realms.goodstype')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realms.realm')),
            ],
            options={
                'unique_together': {('realm', 'goods_type')},
            },
        ),
        migrations.AddField(
            model_name='realm',
            name='goods',
            field=models.ManyToManyField(related_name='realms_with_goods', through='realms.RealmGoodsType', to='realms.goodstype'),
        ),
        migrations.CreateModel(
            name='RealmMercenaryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_rating', models.DecimalField(decimal_places=2, default=1.0, help_text="A measure of the unit's overall combat effectiveness. Can be fractional (e.g., 0.5 for CR 1/2).", max_digits=5)),
                ('mercenary_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_types', to='realms.mercenaryunitsize')),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realms.populationrace')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercenary_units', to='realms.realm')),
            ],
            options={
                'verbose_name_plural': 'Realm Mercenary Units',
            },
        ),
        migrations.CreateModel(
            name='RealmMilitaryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1, help_text='Base level of the unit type, affects stats and costs.')),
                ('military_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_types', to='realms.militaryunitsize')),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realms.populationrace')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='military_units', to='realms.realm')),
            ],
            options={
                'verbose_name_plural': 'Realm Military Units',
            },
        ),
        migrations.AddField(
            model_name='realm',
            name='scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realms.realmscale'),
        ),
        migrations.CreateModel(
            name='RealmResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realms.realm')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realms.resource')),
            ],
            options={
                'unique_together': {('realm', 'resource')},
            },
        ),
        migrations.AddField(
            model_name='realm',
            name='resources',
            field=models.ManyToManyField(related_name='realms_with_resource', through='realms.RealmResource', to='realms.resource'),
        ),
        migrations.AddField(
            model_name='goodstype',
            name='cost_resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_costing_this_resource', to='realms.resource'),
        ),
        migrations.AddField(
            model_name='realm',
            name='season',
            field=models.ForeignKey(default='Spring', null=True, on_delete=django.db.models.deletion.PROTECT, to='realms.season'),
        ),
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('action_key', models.CharField(help_text="A unique key for game logic, e.g., 'buy_resources'.", max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.PositiveIntegerField(default=0)),
                ('descriptors', models.ManyToManyField(blank=True, to='realms.descriptor')),
                ('available_seasons', models.ManyToManyField(blank=True, to='realms.season')),
            ],
        ),
        migrations.CreateModel(
            name='StrongholdInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Custom name for this stronghold, defaults to type name.', max_length=100)),
                ('land_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stronghold', to='realms.landunit')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strongholds', to='realms.realm')),
                ('stronghold_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='realms.strongholdtype')),
            ],
        ),
        migrations.CreateModel(
            name='StrongholdImprovementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('benefits', models.JSONField(default=dict, help_text="JSON dictionary of benefits, e.g., {'trade_income_modifier': 0.1, 'unit_training_speed': -0.1}")),
                ('duration_seasons', models.PositiveIntegerField(default=1, help_text='Number of seasons (turns) it takes to build/upgrade.')),
                ('population_cost', models.PositiveIntegerField(default=1, help_text='Population units required for construction/upgrade.')),
                ('resource_costs', models.JSONField(default=dict, help_text="JSON dictionary of resource costs, e.g., {'Wood': 20, 'Iron': 10, 'Gold': 50}")),
                ('gold_cost', models.PositiveIntegerField(default=0, help_text='Gold cost for construction.')),
                ('gold_upkeep_cost', models.PositiveIntegerField(default=0, help_text='Gold upkeep cost per year after construction.')),
                ('prerequisite_stronghold_types', models.ManyToManyField(blank=True, help_text='Stronghold types required to build this improvement.', to='realms.strongholdtype')),
            ],
        ),
        migrations.CreateModel(
            name='StrongholdImprovementInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('improvement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='realms.strongholdimprovementtype')),
                ('stronghold_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvements', to='realms.strongholdinstance')),
            ],
            options={
                'unique_together': {('stronghold_instance', 'improvement_type')},
            },
        ),
    ]
