# Generated by Django 5.2 on 2025-05-21 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(default='')),
                ('value', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='LandUnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('production', models.JSONField(default=dict)),
                ('harvest', models.IntegerField(default=1)),
                ('settlement_capacity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PopulationRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Realm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ruler', models.CharField(max_length=100)),
                ('treasury', models.IntegerField(default=0)),
                ('season', models.CharField(default='Spring', max_length=10)),
                ('year', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='RealmScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(default='')),
                ('pop_unit_size', models.IntegerField(default=1)),
                ('land_unit_size', models.IntegerField(default=1)),
                ('gold_unit_value', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='LandUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('assigned_population', models.JSONField(default=list)),
                ('upgrades', models.JSONField(default=list)),
                ('mineral_type', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realms.landunittype')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_units', to='realms.realm')),
            ],
        ),
        migrations.CreateModel(
            name='PopulationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pop_units', to='realms.landunit')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realms.populationrace')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='population_units', to='realms.realm')),
            ],
        ),
        migrations.CreateModel(
            name='OngoingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=100)),
                ('start_season', models.CharField(max_length=10)),
                ('start_year', models.IntegerField()),
                ('duration', models.IntegerField(default=1)),
                ('completed', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, null=True)),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realms.realm')),
            ],
        ),
        migrations.CreateModel(
            name='RealmGoodsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('goods_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realms.goodstype')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realms.realm')),
            ],
            options={
                'unique_together': {('realm', 'goods_type')},
            },
        ),
        migrations.AddField(
            model_name='realm',
            name='goods',
            field=models.ManyToManyField(related_name='realms_with_goods', through='realms.RealmGoodsType', to='realms.goodstype'),
        ),
        migrations.AddField(
            model_name='realm',
            name='scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realms.realmscale'),
        ),
        migrations.CreateModel(
            name='RealmResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realms.realm')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realms.resource')),
            ],
            options={
                'unique_together': {('realm', 'resource')},
            },
        ),
        migrations.AddField(
            model_name='realm',
            name='resources',
            field=models.ManyToManyField(related_name='realms_with_resource', through='realms.RealmResource', to='realms.resource'),
        ),
    ]
