# Generated by Django 5.2 on 2025-05-06 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandUnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('production', models.JSONField(default=dict)),
                ('harvest', models.IntegerField(default=1)),
                ('settlement_capacity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Realm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ruler', models.CharField(max_length=100)),
                ('treasury', models.IntegerField(default=0)),
                ('resources', models.JSONField(default=dict)),
                ('season', models.CharField(default='Spring', max_length=10)),
                ('year', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='LandUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('assigned_population', models.JSONField(default=list)),
                ('upgrades', models.JSONField(default=list)),
                ('mineral_type', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realms.landunittype')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_units', to='realms.realm')),
            ],
        ),
        migrations.CreateModel(
            name='PopulationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(max_length=50)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pop_units', to='realms.landunit')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='population_units', to='realms.realm')),
            ],
        ),
    ]
