# Generated by Django 5.2 on 2025-07-22 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ongoingaction',
            name='start_season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='realms.season'),
        ),
    ]
