# Generated by Django 5.2 on 2025-05-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landunit',
            name='choices',
        ),
        migrations.AddField(
            model_name='landunittype',
            name='choices',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
