# Generated by Django 5.2 on 2025-05-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='value',
            new_name='gold_equivalent',
        ),
    ]
