# Generated by Django 5.2 on 2025-07-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0002_alter_ongoingaction_start_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontype',
            name='inputs',
            field=models.JSONField(blank=True, default=list, help_text='A list of input field definitions for the action form.'),
        ),
        migrations.AddField(
            model_name='actiontype',
            name='submit_text',
            field=models.CharField(default='Start Action', max_length=50),
        ),
    ]
