# Generated by Django 5.2 on 2025-05-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0002_rename_value_resource_gold_equivalent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='gold_equivalent',
        ),
        migrations.AddField(
            model_name='resource',
            name='value',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
        ),
    ]
