# Generated by Django 5.2 on 2025-05-07 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0002_remove_landunit_choices_landunittype_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landunittype',
            name='choices',
        ),
    ]
