# Generated by Django 5.2 on 2025-05-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0003_remove_landunittype_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
