# Generated by Django 5.2 on 2025-05-21 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0003_remove_resource_gold_equivalent_resource_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='cost_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goodstype',
            name='cost_resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_costing_this_resource', to='realms.resource'),
        ),
        migrations.AddField(
            model_name='goodstype',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
