# Generated by Django 5.2 on 2025-07-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0003_actiontype_inputs_actiontype_submit_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontype',
            name='seasonal_modifications',
            field=models.JSONField(blank=True, default=dict, help_text="JSON with modifications for specific seasons. E.g., {'Summer': {'cost_multiplier': 1.5}}"),
        ),
    ]
