# Generated by Django 5.2 on 2025-05-07 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0004_populationrace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populationunit',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realms.populationrace'),
        ),
    ]
