# Generated by Django 5.2 on 2025-05-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0004_goodstype_cost_quantity_goodstype_cost_resource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='gold_cost_display',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
