# Generated by Django 5.2 on 2025-07-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0004_actiontype_seasonal_modifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoingaction',
            name='assigned_population',
            field=models.ManyToManyField(blank=True, related_name='assigned_action', to='realms.populationunit'),
        ),
        migrations.AddField(
            model_name='populationunit',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('busy', 'Busy')], default='idle', max_length=10),
        ),
    ]
