# Generated by Django 5.2 on 2025-05-26 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0005_resource_gold_cost_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercenaryUnitSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('gold_cost_recruitment_modifier', models.DecimalField(decimal_places=3, default=1.0, max_digits=5)),
                ('food_cost_upkeep', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='MilitaryUnitSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('gold_cost_upkeep', models.IntegerField(default=1, help_text='Base gold cost for upkeep per unit of this size category per year.')),
                ('food_cost_upkeep', models.IntegerField(default=1, help_text='Base food cost for upkeep per unit of this size category per year.')),
            ],
        ),
        migrations.CreateModel(
            name='StrongholdType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('duration_seasons', models.PositiveIntegerField(default=1, help_text='Number of seasons (turns) it takes to build.')),
                ('population_cost', models.PositiveIntegerField(default=1, help_text='Population units required for construction.')),
                ('resource_costs', models.JSONField(default=dict, help_text="JSON dictionary of resource costs, e.g., {'Wood': 50, 'Stone': 20, 'Gold': 100}")),
                ('population_capacity_bonus', models.IntegerField(default=0, help_text='Bonus to population capacity.')),
            ],
        ),
        migrations.RenameField(
            model_name='landunittype',
            old_name='settlement_capacity',
            new_name='base_population_capacity',
        ),
        migrations.AddField(
            model_name='landunit',
            name='has_mine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landunit',
            name='has_roads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realm',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='realm',
            name='loyalty_mercenaries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realm',
            name='loyalty_military',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realm',
            name='loyalty_population',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realmscale',
            name='military_unit_size',
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='landunit',
            name='assigned_population',
        ),
        migrations.AlterField(
            model_name='realm',
            name='treasury',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='RealmMercenaryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_rating', models.DecimalField(decimal_places=2, default=1.0, help_text="A measure of the unit's overall combat effectiveness. Can be fractional (e.g., 0.5 for CR 1/2).", max_digits=5)),
                ('mercenary_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_types', to='realms.mercenaryunitsize')),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realms.populationrace')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercenary_units', to='realms.realm')),
            ],
            options={
                'verbose_name_plural': 'Realm Mercenary Units',
            },
        ),
        migrations.CreateModel(
            name='RealmMilitaryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1, help_text='Base level of the unit type, affects stats and costs.')),
                ('military_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_types', to='realms.militaryunitsize')),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realms.populationrace')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='military_units', to='realms.realm')),
            ],
            options={
                'verbose_name_plural': 'Realm Military Units',
            },
        ),
        migrations.CreateModel(
            name='StrongholdInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Custom name for this stronghold, defaults to type name.', max_length=100)),
                ('land_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stronghold', to='realms.landunit')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strongholds', to='realms.realm')),
                ('stronghold_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='realms.strongholdtype')),
            ],
        ),
        migrations.CreateModel(
            name='StrongholdImprovementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('benefits', models.JSONField(default=dict, help_text="JSON dictionary of benefits, e.g., {'trade_income_modifier': 0.1, 'unit_training_speed': -0.1}")),
                ('duration_seasons', models.PositiveIntegerField(default=1, help_text='Number of seasons (turns) it takes to build/upgrade.')),
                ('population_cost', models.PositiveIntegerField(default=1, help_text='Population units required for construction/upgrade.')),
                ('resource_costs', models.JSONField(default=dict, help_text="JSON dictionary of resource costs, e.g., {'Wood': 20, 'Iron': 10, 'Gold': 50}")),
                ('gold_upkeep_cost', models.PositiveIntegerField(default=0, help_text='Gold upkeep cost per year after construction.')),
                ('prerequisite_stronghold_types', models.ManyToManyField(blank=True, help_text='Stronghold types required to build this improvement.', to='realms.strongholdtype')),
            ],
        ),
        migrations.AddField(
            model_name='landunit',
            name='assigned_population',
            field=models.ManyToManyField(blank=True, related_name='located_in_land_units', to='realms.populationunit'),
        ),
        migrations.CreateModel(
            name='StrongholdImprovementInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('improvement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='realms.strongholdimprovementtype')),
                ('stronghold_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvements', to='realms.strongholdinstance')),
            ],
            options={
                'unique_together': {('stronghold_instance', 'improvement_type')},
            },
        ),
    ]
