# Generated by Django 5.2 on 2025-05-19 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0005_alter_populationunit_race'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealmScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(default='')),
                ('pop_unit_size', models.IntegerField(default=1)),
                ('land_unit_size', models.IntegerField(default=1)),
                ('gold_unit_value', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='realm',
            name='scale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='realms.realmscale'),
        ),
    ]
