# Generated by Django 5.2 on 2025-08-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0005_ongoingaction_assigned_population_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodstype',
            name='cost_quantity',
        ),
        migrations.RemoveField(
            model_name='goodstype',
            name='cost_resource',
        ),
        migrations.AddField(
            model_name='goodstype',
            name='cost_in_gold',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Base cost in gold to produce one unit.', max_digits=10),
        ),
        migrations.AddField(
            model_name='goodstype',
            name='required_resource_category',
            field=models.CharField(blank=True, help_text='If production requires a resource from a specific category (e.g., Minerals).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.CharField(blank=True, help_text='e.g., Minerals, Lumber', max_length=50, null=True),
        ),
    ]
