# Generated by Django 5.2 on 2025-08-13 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0006_remove_goodstype_cost_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='required_resource_specific',
            field=models.ForeignKey(blank=True, help_text='If production requires one specific resource (e.g., Iron).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='realms.resource'),
        ),
    ]
