# Generated by Django 5.2 on 2025-05-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0006_mercenaryunitsize_militaryunitsize_strongholdtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strongholdtype',
            name='gold_cost',
            field=models.PositiveIntegerField(default=0, help_text='Gold cost for construction.'),
        ),
        migrations.AlterField(
            model_name='strongholdtype',
            name='resource_costs',
            field=models.JSONField(default=dict, help_text="JSON dictionary of resource costs, e.g., {'Wood': 50, 'Stone': 20}"),
        ),
    ]
