# Generated by Django 5.2 on 2025-05-19 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0006_realmscale_realm_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realms.realmscale'),
        ),
    ]
