# Generated by Django 5.2 on 2025-05-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0007_strongholdtype_gold_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strongholdimprovementtype',
            name='gold_cost',
            field=models.PositiveIntegerField(default=0, help_text='Gold cost for construction.'),
        ),
    ]
