# Generated by Django 5.2 on 2025-08-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0007_goodstype_required_resource_specific'),
    ]

    operations = [
        migrations.AddField(
            model_name='strongholdtype',
            name='production_capacity',
            field=models.PositiveIntegerField(default=1, help_text='Number of population units that can be assigned to production actions per season.'),
        ),
    ]
