# Generated by Django 5.2 on 2025-05-19 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0007_alter_realm_scale'),
    ]

    operations = [
        migrations.CreateModel(
            name='OngoingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=100)),
                ('start_season', models.CharField(max_length=10)),
                ('start_year', models.IntegerField()),
                ('duration', models.IntegerField(default=1)),
                ('completed', models.BooleanField(default=False)),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realms.realm')),
            ],
        ),
    ]
