# Generated by Django 5.2 on 2025-05-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0008_ongoingaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoingaction',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
